### ISSUE TITLE
Possibility for array definition

### ISSUE THREAD

**Issue by philmas** [jill64/svelte-qparam#32]
I cam across your plugin. It looks rather simple and accessible which is great.

I was wondering whether it is possible to define and obtain array information? If I would define `?str=hello&str=world`, I could obtain and set this information.

**Comment by jill64** [comment]
Thank you for the feedback !

Currently array parameters are not supported, but this is a common use case, so it's worth supporting.

For example

````svelte
<script>
  import { qparam, array } from 'svelte-qparam'
  import { string } from 'svelte-qparam/serde'

  // https://example.com/?str=hello&str=world
  $: str = qparam('str', array(string))

  // output ['hello', 'world']
  $: console.log($str)

  // navigate to https://example.com/?str=foo&str=bar&str=baz
  $str = ['foo', 'bar', 'baz']
</script>
````

What do you think of this idea?
